// Code generated by Slice Machine. DO NOT EDIT.

import Markdown from './Markdown';
import MktOneColumn from './MktOneColumn';
import MktTwoColumnSideImage from './MktTwoColumnSideImage';
import TitleIntroduction from './TitleIntroduction';

export {
	Markdown,
	MktOneColumn,
	MktTwoColumnSideImage,
	TitleIntroduction,
};

export const components = {
	markdown: Markdown,
	mkt_one_column: MktOneColumn,
	mkt_two_column_side_image: MktTwoColumnSideImage,
	title_introduction: TitleIntroduction,
};
